[package]
name = "my-gp-contract"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "my_gp_contract"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
async-compression = "=0.3.7"
bumpalo = "=3.9.0"
mio = "=0.7"
solana-system-program = "=1.17.34"
tokio = "=1.24.2"
libc = "0.2"
socket2 = "0.4"
