[toolchain]
anchor_version = "0.26.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_gp_contract = "CsyFSB4fUHaFmtwhWMBqoUrcXdiQHnwWLiRjsL1aKiYi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"